### PR TITLE
add save file dialog support

### PR DESCRIPTION
**Pull request by f69**
- add save file dialog support for all platforms (with default filename)
- modified tests for linux and macos
- modified macos result parsing to always include volume name (dont know if this right, but on my Mac Book main volume has long name)

### CODE REVIEW

**Comment by philenius** [comment]
Thank you for putting so much effort into your pull request, @f69. Also, thank you for changing the result on macOS to always include `/Volume/` (I have never used a mac before and didn't know this). Thank you for reading my code and for writing tests. Good work!
I'll review and merge your pull request this weekend!

**Comment by f69** [comment]
Thank you for your work!

Aproach with volume name in returned path is not perfect, but it works (at least for me).
You can get nore information here: [Referencing Files and Folders in AppleScript](https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/ReferenceFilesandFolders.html)
From information above I've found better solution - get POSIX format from osascript, but haven't implemented it yet in production ready quality, because I'm searching for solution for [issue #6](https://github.com/philenius/flutter_file_picker_desktop/issues/6#issue-957955287).

Another thing I have missed in PR is test for Windows. It copies test files to C:\Temp, but doesn't use them at all. And finally it **deletes C:\Temp**! I think, it's not good, even if it is assumed, that C:\Temp is temporary directory. So, I'd propose to use code like these (if you plan to develop this test further and to use test files):
```
  final testRoot = r'C:\Temp\file_picker_desktop\';
  final assetRoot = r'.\test\test_files\';
  final yamlTestFile = 'test.yml';

  setUpAll(() {
    Directory(testRoot).createSync(recursive: true);
    File(assetRoot + yamlTestFile).copySync(testRoot + yamlTestFile);
  });

  tearDownAll(() {
    Directory(testRoot).deleteSync(recursive: true);
  });
````

**Comment by f69** [comment]
But maybe all this has no sense, because of [file_selector](https://pub.dev/packages/file_selector) and [file_selector_windows](https://pub.dev/packages/file_selector_windows), [file_selector_macos](https://pub.dev/packages/file_selector_macos), [file_selector_linux](https://pub.dev/packages/file_selector_linux)?

**Comment by philenius** [comment]
@f69 thank you again. I deleted the test setup which created dummy files and finally recursively deleted `C:\temp`. Even though the unit tests are executed via GitHub Actions in a virtual environment it might not have been the best idea.

I found out about the official implementations from Flutter / Google, too. And no, it doesn't really make sense to continue working on this project due to Google working on a official implementation. Although, the Google developers state that they don't endorse the usage of their current releases because they lack a testing infrastructure:

> This folder contains unendorsed desktop implementations of the file_selector plugin. They are not currently endorsed, and are here rather than in the flutter/plugins repository, because there is not yet test infrastructure in place to test desktop plugins that show native UI, and so these implementations don't meet the Flutter testing requirements. Once automated tests are developed, they will be moved to flutter/plugins and endorsed.
Source: https://github.com/google/flutter-desktop-embedding/blob/master/plugins/file_selector/README.md

Let's see how long it will take until the `file_selector` plugins are officially released and endorsed by Google :wink:

**Pull request merged**
